_wandb:
    value:
        cli_version: 0.22.2
        e:
            5sx3mbkbz65q41aq0imhpw1lxdd7jbo4:
                codePath: Imagenette\Task1_Imagenette.ipynb
                codePathLocal: Task1_Imagenette.ipynb
                cpu_count: 14
                cpu_count_logical: 20
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "491900628992"
                        used: "260340809728"
                email: octaviorevetria@gmail.com
                executable: c:\Users\Octav\miniconda3\envs\taller_dl\python.exe
                git:
                    commit: 4f4717d1336e82f5efb0152a5399c6abbf63692d
                    remote: https://github.com/octarevetria/Taller_Deep_Learning.git
                gpu: NVIDIA GeForce RTX 3050 Ti Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 2560
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce RTX 3050 Ti Laptop GPU
                      uuid: GPU-30df4ca8-e6dc-3644-cb7b-21fbecd843f1
                host: Laptop_Octa
                memory:
                    total: "16849293312"
                os: Windows-10-10.0.26100-SP0
                program: c:\Users\Octav\posgrado\Repositorios Master\taller dl\Imagenette\Task1_Imagenette.ipynb
                python: CPython 3.11.13
                root: c:\Users\Octav\posgrado\Repositorios Master\taller dl\Imagenette
                startedAt: "2025-10-27T02:54:16.775813Z"
                writerId: 5sx3mbkbz65q41aq0imhpw1lxdd7jbo4
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 2
                - 16
            "4": 3.11.13
            "5": 0.22.2
            "8":
                - 1
                - 3
            "12": 0.22.2
            "13": windows-amd64
architecture:
    value: CNN_3C_BN
batch_size:
    value: 64
dataset:
    value: Imagenette
epochs:
    value: 30
learning_rate:
    value: 0.001
optimizer:
    value: Adam
